### ISSUE TITLE
Some bugs in Quick Start Guide in README.md

### ISSUE THREAD

**Issue by Leolty** [asyml/ForteHealth#32]
**Describe the bug**
I followed the instructions of Python code in the Quick Start Guide, and I found some bugs that needed to be fixed:
In the following codes:
```python
pl.add(SpacyProcessor(), config={
    processors: ["sentence", "tokenize", "pos", "ner", "umls_link"],
    medical_onto_type: "ftx.medical.clinical_ontology.MedicalEntityMention"
    umls_onto_type: "ftx.medical.clinical_ontology.UMLSConceptLink"
    lang: "en_ner_bc5cdr_md"
    })
```
_processors, medical_onto_type, umls_onto_type, lang_ need double quatation marks;
and some commas are also needed.

I will pull a request to give the codes I successfully debug. 

**To Reproduce**
1. follow all the instructions in README.md (copy)
2. run 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Compiler: Spyder

**Comment by Piyush13y** [comment]
@Leolty  Sounds good. It would be great if you could create a PR for these changes as soon as possible; you can add me as a reviewer. Just want to make sure we push these Readme changes immediately, so no one else faces the same issue while setting up ForteHealth.

**Comment by Piyush13y** [comment]
Pushing the changes for this since I feel its time sensitive to have a working readme. Feel free to propose any more changes based on your experience with the sample code.
