### ISSUE TITLE
Fix abbreviation detector in Scispacy processor

### ISSUE THREAD

**Issue by nikhilranjan7** [asyml/ForteHealth#70]
Describe the bug
Incorrect index for begin and end in abbreviation detection processor

To Reproduce
Run Scispacy processor for abbreviation detection

Expected behavior
Example:

"Spinal and bulbar muscular atrophy (SBMA) is an \
  inherited motor neuron disease caused by the expansion \
  of a polyglutamine tract within the androgen receptor (AR)."

long_form = Spinal and bulbar muscular atrophy
Stored long_form in tmp_abrv.text is just one letter character due to incorrect indexing

**Comment by Piyush13y** [comment]
@nikhilranjan7  It would be great if you could add some description to these issues, this and the index search optimization one. Its helpful if  someone is tracking an old issue or if they are trying to find an issue to work on, based on their bandwidth, etc.
